config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(params_flat)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def params_flat
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <h1 class="my-3">All our flats (<%= (Flat.count) %>)</h1>

  <div class="row">
    <% @flats.each do |flat| %>
    <div class="card col-4">
      <div class="card-body">
        <h5 class="card-title"><%= flat.name %></h5>
        <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
        <p class="card-text"><%= flat.description %></p>
        <p class="card-text"><%= flat.number_of_guests %> <i class="fa-solid fa-user-group"></i></p>
        <p><%= flat.price_per_night %> <i class="fa-solid fa-euro-sign"></i></p>
        <%= link_to("More info", flat_path(flat), class:"btn btn-primary") %>
      </div>
    </div>
    <% end %>
  </div>

</div>

<%= link_to "Add a new flat", new_flat_path %>

app/views/flats/new.html.erb
<%= simple_form_for @flat do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :description %>
<%= f.input :price_per_night %>
<%= f.input :number_of_guests %>
<%= f.submit %>
<% end %>

app/views/flats/show.html.erb
<h2><%= @flat.name %></h2>
<p><%= @flat.address %></p>
<p><%= @flat.description %></p>
<p><%= @flat.price_per_night %></p>
<p><%= @flat.number_of_guests %></p>

<%= link_to "Back to all flats", flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>